---
version: 2

updates:
  # Enable version updates for pip dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "imewei"
    assignees:
      - "imewei"
    open-pull-requests-limit: 10
    # Group dependency updates to reduce PR noise
    groups:
      # Group all JAX-related packages together
      jax-ecosystem:
        patterns:
          - "jax*"
          - "numpyro"
          - "optax"
          - "flax"
      # Group testing dependencies
      testing:
        patterns:
          - "pytest*"
          - "hypothesis"
      # Group documentation dependencies
      docs:
        patterns:
          - "sphinx*"
          - "numpydoc"
      # Group linting/formatting tools
      dev-tools:
        patterns:
          - "ruff"
          - "mypy"
          - "pre-commit"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "imewei"
    assignees:
      - "imewei"
    open-pull-requests-limit: 5
