---
# Read the Docs configuration file for piblin-jax
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

# Build PDF and EPUB formats (optional)
formats:
  - pdf
  - epub

# Python configuration
python:
  install:
    # Install piblin-jax package with documentation dependencies
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      # Verify piblin-jax installation
      - python -c "import piblin_jax; print(piblin_jax.__version__)"

# Search configuration
search:
  ranking:
    # Boost ranking for API reference pages
    api/*: 2
  ignore:
    # Don't index these patterns
    - _build/*
    - .git/*

# Submodules configuration (if using git submodules)
submodules:
  include: []
  recursive: false
