name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    name: Build and verify documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"

    - name: Build Sphinx documentation
      run: |
        cd docs
        make html 2>&1 | tee build.log

    - name: Check for warnings
      run: |
        cd docs
        if grep -i "WARNING\|CRITICAL" build.log; then
          echo "❌ Documentation build has warnings or critical errors!"
          echo "Please fix the warnings above before merging."
          exit 1
        else
          echo "✅ Documentation built successfully with no warnings!"
        fi

    - name: Upload documentation artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/_build/html/
        retention-days: 7

    - name: Upload build log on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: docs/build.log
        retention-days: 7
